# Generated by Django 6.0.3 on 2026-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_slots',
            name='slot_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
