# Generated by Django 6.0.3 on 2026-03-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
