# Generated by Django 6.0.3 on 2026-03-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_services_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
