# Generated by Django 6.0.3 on 2026-03-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_services_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='service_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
