# Generated by Django 6.0.3 on 2026-04-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_services_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='duration_minutes',
            field=models.IntegerField(default=120),
        ),
    ]
