# Generated by Django 6.0.3 on 2026-03-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='payment_pin',
            field=models.CharField(default='4040', max_length=4),
        ),
    ]
