# Generated by Django 6.0.3 on 2026-03-17 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('parking', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('service_date', models.DateField()),
                ('car_brand', models.CharField(default=True, max_length=50)),
                ('car_model', models.CharField(default=True, max_length=50)),
                ('car_color', models.CharField(default=True, max_length=30)),
                ('car_reg_num', models.CharField(default=True, max_length=10)),
                ('booking_status', models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='customers.customers')),
                ('parking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking', to='parking.parking_slots')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service', to='services.services')),
            ],
        ),
    ]
