# Generated by Django 6.0.3 on 2026-03-24 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_history_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking_history',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Paid', 'Paid')], default='Unpaid', max_length=30),
        ),
        migrations.AlterField(
            model_name='booking_history',
            name='booking_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
