# Generated by Django 6.0.3 on 2026-03-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_history_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='car_reg_num',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
