# Generated by Django 6.0.3 on 2026-04-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_history_car_reg_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_history',
            name='service_time',
            field=models.CharField(default='10:00 AM', max_length=20),
        ),
    ]
